### ISSUE TITLE
Request: add support for `regex::bytes::Regex`

### ISSUE THREAD

**Issue by bnoctis** [Canop/lazy-regex#11]
The doc of `regex::bytes` says:

> This module provides a nearly identical API to the one found in the top-level of this crate. There are two important differences:
>   1. Matching is done on &[u8] instead of &str. Additionally, Vec<u8> is used where String would have been used.
>   2. Unicode support can be disabled even when disabling it would result in matching invalid UTF-8 bytes.

So hopefully the change would be as easy as changing from `pub regex: regex::Regex` to `pub regex: regex::bytes::Regex`.
If there are no more to consider, I'll happily make a PR.

**Comment by bnoctis** [comment]
Either a `_bytes` prefix, or a `bytes` submodule like what `regex` did, looks OK to me.

**Comment by Canop** [comment]
I'll confess I lack time currently (war, work, etc.).
If you think you can make this cleanly enough (limiting code duplication, if possible), I'm fine with the idea of a PR (no promise I'll merge it: I really need to be confident in the quality before I merge anything in this quite critical crate).

**Comment by bnoctis** [comment]
Yeah, understand that. I'll consider quality over quantity too.

Thinking of it, the submodule take may collide with the string version.
Don't know how `regex` people decided on it, but I'd prefer a suffix version:

```rust
let bytes_re = lazy_regex::lazy_regex_bytes!("(byte )?string");
// or
let bytes_re = lazy_regex::bytes::lazy_regex!("(byte )?string");

// but!
use lazy_regex::lazy_regex;
use lazy_regex::bytes::lazy_regex;
// unless
use lazy_regex::{lazy_regex, bytes::lazy_regex as lazy_regex_bytes};
```

**Comment by bnoctis** [comment]
Adding `From<proc_macro::TokenStream>` for `RegexCode` seems to save some lines in macro implementations. Is there a reason not to do so?

**Comment by Canop** [comment]
I don't really remember, it's probably just how it happened. No objection for the change.

**Comment by bnoctis** [comment]
OK. As to save more lines, what's your preference towards using closures? That saves every macro from several lines of boilerplate code, but, uh, it uses closures.

**Comment by Canop** [comment]
I'm not sure I follow you (can't dive in the code right now). It's those are compile time executed closures, and they're clear enough (comments welcome), no problem.

**Comment by bnoctis** [comment]
Yes they are compile-time.

Playing with macros, it seems possible to add
- a non-standard suffix flag,
  ```rust
  let bytes_re = lazy_regex!("(byte)?string"B);
  ```
- or an optional suffix string ("bytes"),
  ```rust
  let bytes_re = lazy_regex!("(byte)?string", bytes);
  ```
to indicate a bytes variant is wanted.

Since we provide only macros, that seems feasible to me. Opinion?
