### ISSUE TITLE
feature "std" is always required

### ISSUE THREAD

**Issue by jonassmedegaard** [Canop/lazy-regex#16]
I have packaged lazy-regex for Debian, and as part of CI routines set it up to build with each feature separately - but all of those except "std" fail like this:

```
error: `std` feature is currently required to build this crate
   --> /tmp/tmp.mLGTluLWVL/registry/regex-1.6.0/src/lib.rs:613:1
    |
613 | compile_error!("`std` feature is currently required to build this crate");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `crate::Error`
  --> /tmp/tmp.mLGTluLWVL/registry/regex-1.6.0/src/compile.rs:16:5
   |
16 | use crate::Error;
   |     ^^^^^^^-----
   |     |      |
   |     |      help: a similar name exists in the module: `error`
   |     no `Error` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `regex` due to 2 previous errors
```

Patching `Cargo.toml` to enable feature "std" for all other features succeeds, but I suspect that to be a workaround, and the real fix is to somehow allow code to build without "std" feature.

**Comment by Canop** [comment]
I don't get it. How exactly do you produce this error ?

And what do you mean with " allow code to build without "std" feature" ?

**Comment by jonassmedegaard** [comment]
E.g. building the crate with cargo options "--all-targets --no-default-features --features perf".

**Comment by Canop** [comment]
Does that look OK for you now ?

**Comment by jonassmedegaard** [comment]
Yes, perfect now. Thanks!
