### ISSUE TITLE
Question about MSRV

### ISSUE THREAD

**Issue by Xuanwo** [Canop/lazy-regex#18]
Hi, is there a solid reason to bump MSRV to 1.65?

I didn't see to much new std API used in recent changes. If it possible to downgrade MSRV to 1.60 instead? Thanks in advance.

Our tests failed for this change: https://github.com/datafuselabs/opendal/actions/runs/3847259619/jobs/6553502089

**Comment by Canop** [comment]
There's a reason, it allows for some prettier code, but a downgrade is very possible.

Why are you stuck on 1.60 ?

**Comment by Xuanwo** [comment]
> Why are you stuck on 1.60 ?

One of our most significant users decides to keep on `1.60`, so...

> but a downgrade is very possible.

It could be a very good news for us if you decide to downgrade :heart:

**Comment by Canop** [comment]
> It could be a very good news for us if you decide to downgrade

I'll downgrade. Looking for the best version.

**Comment by Xuanwo** [comment]
> I'll downgrade. Looking for the best version (1.58 or before).

Thanks a lot!

**Comment by Canop** [comment]
No pb: you're not the first one having [a problem with this version](https://github.com/Canop/lazy-regex/issues/17) and I just realized I didn't even use the 1.65 feature I wanted to use...

**Comment by Canop** [comment]
Can you check it's OK for you now ?

**Comment by Xuanwo** [comment]
> Can you check it's OK for you now ?

2.4.1 works on 1.60 now! Thanks.
