### ISSUE TITLE
regex_replace and regex_replace_all should expect any expression, not just a closure

### ISSUE THREAD

**Issue by nikis05** [Canop/lazy-regex#19]
Methods [Regex::replace](https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace) and [Regex::replace_all](https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace_all) accept a `Replacer`, which allows passing both closures as well as just strings / string slices in simple cases.

However, `lazy_regex::replace` and `replace_all` expect an `ExprClosure`, which makes it impossible to use them like this:

```rust
let text = "UwU";
let output = replace_all!("U", text, "O");
assert_eq(&output, "OwO");
```

Macros should lift this restriction and expect just any `Expr`.

**Comment by Canop** [comment]
This wasn't so trivial as to just use any Expr, because the added value is partly in checking and explaining why it doesn't work. When the replacer is a closure, it's important to have the number of groups checked at compile time.

Can you tell me if PR #20  looks good for you ?

**Comment by nikis05** [comment]
Cool, didn't realise it also checks number of groups at compile time. Looks good to me, thanks.
