### ISSUE TITLE
`lazy-regex` is causing an Internal Compilation Error

### ISSUE THREAD

**Issue by satvikpendem** [Canop/lazy-regex#21]
I wrote about this in more detail here: https://github.com/rust-lang/rust/issues/109640

I made a minimal example using only the `lazy-regex` crate and it seems to cause an ICE.

**Comment by clubby789** [comment]
This is an issue for Rust, and your code triggered the ICE rather than anything specific to `lazy-regex`

**Comment by satvikpendem** [comment]
Thanks, just wanted to let you know in case either way, looks like it's been fixed as you mentioned on the linked Rust issue.
