### ISSUE TITLE
Request: Support /.../i syntax

### ISSUE THREAD

**Issue by nicoburns** [Canop/lazy-regex#3]
Raw strings are great for avoiding escaping issues, however they add quite a bit of noise to the syntax. I was wondering if you would consider supporting the familiar `/pattern/flags` syntax that languages such as sed and javascript use, such that

```
regex!(/^\s*("[a-t]*"\s*)+$/i);
```
would be equivalent to:
```
regex!(r#"^\s*("[a-t]*"\s*)+$"#i);
```

(except that `/`'s would need to be escaped in the `/pattern/flags` syntax)

**Comment by Canop** [comment]
The reason I didn't include it was that I wasn't very enthusiastic for handling escapings myself, I preferred to use the standard string parsing.

But I'll have a look if I'm not the only one interested in this syntax.

**Comment by Canop** [comment]
I don't think it's possible today: Rust's lexer doesn't want to tokenize something as simple as `/"/`.

**Comment by Canop** [comment]
I'm closing this issue as *"probably not possible in any reasonable way"*.
