### ISSUE TITLE
Feature request:  regex_captures_iter!() macro

### ISSUE THREAD

**Issue by dimo414** [Canop/lazy-regex#37]
It'd be great if there was a macro like `regex_captures!()` that supported iterating over multiple captures like `Regex::captures_iter`. If I'm not mistaken I can't use `regex_captures!()` or any of the other helper macros in this crate (aside from `regex!()`) to iterate over multiple captures easily.

**Comment by Canop** [comment]
> If I'm not mistaken

You're not.

**Comment by dimo414** [comment]
Thanks!

**Comment by Canop** [comment]
Now available in 3.4.1
